
apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      httpMode: POST
      defaultBucket: air_quality
      organization: my_org
      version: Flux
    secureJsonData:
      token: 5n7quiJsU_dxF_i_vDO0xYhEAqhzMdbEyFOhbTN-uJYdb7ca8JPxvMaNth4_ZssH_8QKsMNVCrbG8wqNT2srog==