{
 "title": "(Per City) Smart Cities: Air Quality Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"air_quality\", tag: \"city\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Air Quality Index (AQI) in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")\n  |> filter(fn: (r) => r[\"_field\"] == \"aqi\")\n  |> filter(fn: (r) => r[\"city\"] == \"${city}\")\n  |> group(columns: [\"city\", \"sensor_type\"])\n  |> mean()\n  |> group(columns: [\"city\"])\n  |> max()\n  |> keep(columns: [\"_value\", \"city\"])"
    }
   ]
  },
  {
   "title": "# Sensors in ${city}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")  \n|> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n|> filter(fn: (r) => r[\"city\"] == \"${city}\") \n|> group(columns: [\"sensor_id\", \"city\"]) \n|> distinct(column: \"sensor_id\") \n|> group() \n|> count(column: \"_value\")  \n|> yield(name: \"total_sensors_panel\")"
    }
   ]
  },
  {
   "title": "Sensor Power Consumption (kW)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"power_consumption\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  },
  {
   "title": "PM10 (µg/m³) Level in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"pm10\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  },
  {
   "title": "PM2.5 (µg/m³) Level in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"pm2_5\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n\n\n"
    }
   ]
  },
  {
   "title": "Temperature (°C) in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  },
  {
   "title": "Humidity (%) in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"humidity\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  },
  {
   "title": "NO2 (µg/m³) Level in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"no2\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  },
  {
   "title": "CO2 (ppm) Levels in ${city}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)  \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")  \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"co2\")  \n  |> filter(fn: (r) => r[\"city\"] == \"${city}\") \n  |> group(columns: [\"city\"]) \n  |> mean()  \n  |> keep(columns: [\"_value\", \"city\"])  \n"
    }
   ]
  }
 ]
}