{
 "title": "(All) Smart Cities: Air Quality Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Air Quality Index (AQI)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\") \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"pm10\" or r[\"sensor_type\"] == \"pm2_5\") \n  |> filter(fn: (r) => r[\"_field\"] == \"aqi\") \n  |> group(columns: [\"city\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sensor Geolocation",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()\n  |> keep(columns: [\"city\", \"latitude\", \"longitude\", \"sensor_id\"])\n  |> unique(column: \"sensor_id\")\n  |> yield(name: \"sensors\")"
    }
   ]
  },
  {
   "title": "AQI Trends Overtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: -7d) \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\") \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"pm2_5\" or r[\"sensor_type\"] == \"pm10\") \n  |> filter(fn: (r) => r[\"_field\"] == \"aqi\") \n  |> group(columns: [\"city\", \"sensor_type\"]) // Group by city and sensor type\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n  |> yield(name: \"mean_aqi\")"
    }
   ]
  },
  {
   "title": "Sensors Per City",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: -1h) \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\") \n  |> group(columns: [\"city\", \"sensor_id\"]) \n  |> distinct(column: \"sensor_id\") \n  |> group(columns: [\"city\"]) \n  |> count(column: \"sensor_id\") \n  |> yield(name: \"sensor_health_per_city\")"
    }
   ]
  },
  {
   "title": "Trends in Air Pollutants Across Cities",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: -1h) \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\") \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"pm2_5\" or r[\"sensor_type\"] == \"pm10\") \n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false) \n  |> group(columns: [\"city\", \"sensor_type\"]) \n  |> yield(name: \"pollution_trends\")"
    }
   ]
  },
  {
   "title": "Weather Trends Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"air_quality\")\n  |> range(start: -1h) \n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor_data\") \n  |> filter(fn: (r) => r[\"sensor_type\"] == \"temperature\" or r[\"sensor_type\"] == \"humidity\") \n  |> aggregateWindow(every: 10m, fn: mean, createEmpty: false) \n  |> group(columns: [\"sensor_type\", \"city\"]) \n  |> keep(columns: [\"_time\", \"_value\", \"city\", \"sensor_type\"]) \n  |> yield(name: \"weather_trends\")"
    }
   ]
  }
 ]
}